# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CiSnitch < Formula
  desc "CI performance analyzer — detects regressions, outliers, and trends in GitHub Actions"
  homepage "https://github.com/vertti/ci-snitch"
  version "0.19.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vertti/ci-snitch/releases/download/v0.19.0/ci-snitch_0.19.0_darwin_amd64.tar.gz"
      sha256 "00516aeca64df329560a8ac794b656f2deae3a153b5429544772a05adbf84dd5"

      define_method(:install) do
        bin.install "ci-snitch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vertti/ci-snitch/releases/download/v0.19.0/ci-snitch_0.19.0_darwin_arm64.tar.gz"
      sha256 "3596107d2ce225b89a9a13f01491340a3e679c963f2cee87c926e25d7cf26acc"

      define_method(:install) do
        bin.install "ci-snitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vertti/ci-snitch/releases/download/v0.19.0/ci-snitch_0.19.0_linux_amd64.tar.gz"
      sha256 "b0dd55e5858ea4b10a67788c407752de06fac500dca05ca8ffa8dc4c386d7a9a"
      define_method(:install) do
        bin.install "ci-snitch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vertti/ci-snitch/releases/download/v0.19.0/ci-snitch_0.19.0_linux_arm64.tar.gz"
      sha256 "161cfd8f2525d69477c3cda381b6a9d276a7965193f0b64a57ac3b3261698fde"
      define_method(:install) do
        bin.install "ci-snitch"
      end
    end
  end

  test do
    system "#{bin}/ci-snitch", "version"
  end
end
