# Generated by pg-tunnel's Homebrew formula workflow. Do not edit.
class PgTunnel < Formula
  desc "Connect PostgreSQL clients to private AWS RDS databases through SSM"
  homepage "https://github.com/vertti/pg-tunnel"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/vertti/pg-tunnel/releases/download/v0.3.0/pg-tunnel_darwin_arm64.tar.xz"
      sha256 "353cf7b3c684aa53283ca703f1fc7393e9f1344277b307fcbd18aa285b7dd0bf"
    end
    on_intel do
      url "https://github.com/vertti/pg-tunnel/releases/download/v0.3.0/pg-tunnel_darwin_amd64.tar.xz"
      sha256 "de6466dce5a7967d666ebae54b97f0c5432d1df4528ea84b2a8835c4728b0dfc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vertti/pg-tunnel/releases/download/v0.3.0/pg-tunnel_linux_arm64.tar.xz"
      sha256 "c54a79a2e317d38dfc5b70bb441ce0230b528bd03ea2d94727c1bb8ad2ddf78d"
    end
    on_intel do
      url "https://github.com/vertti/pg-tunnel/releases/download/v0.3.0/pg-tunnel_linux_amd64.tar.xz"
      sha256 "b164163e8d9d3503815459a16d0815ce536481204c146f7c923e78fbd10a4f1c"
    end
  end

  def install
    bin.install "pg-tunnel"
    doc.install "licenses", "third_party"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pg-tunnel --version 2>&1")
  end
end
