# Generated by pg-tunnel's Homebrew formula workflow. Do not edit.
class PgTunnel < Formula
  desc "Connect PostgreSQL clients to private AWS RDS databases through SSM"
  homepage "https://github.com/vertti/pg-tunnel"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/vertti/pg-tunnel/releases/download/v0.2.1/pg-tunnel_darwin_arm64.tar.xz"
      sha256 "97aa0ed1305da195a46c05eba95e7bbf5f4ab1dc92e2b95148758fc2e1bdc67b"
    end
    on_intel do
      url "https://github.com/vertti/pg-tunnel/releases/download/v0.2.1/pg-tunnel_darwin_amd64.tar.xz"
      sha256 "c73b7927f9346f1ff6369287e22a488c7dcf81ffcff9750b8b856d6f5d76fe06"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vertti/pg-tunnel/releases/download/v0.2.1/pg-tunnel_linux_arm64.tar.xz"
      sha256 "f4ab8028bf06e5665698f2c6f772bba98938b7b816efd00052b14071b85fad4e"
    end
    on_intel do
      url "https://github.com/vertti/pg-tunnel/releases/download/v0.2.1/pg-tunnel_linux_amd64.tar.xz"
      sha256 "313184e6737f83322e2fd294df0df5865655b7b417b74e0c6524794f3627c476"
    end
  end

  def install
    bin.install "pg-tunnel"
    doc.install "licenses", "third_party"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pg-tunnel --version 2>&1")
  end
end
